### ISSUE TITLE
Suggestion (for the bot on Twitter) - mark as automated account

### ISSUE THREAD

**Issue by andypiper** [anotherrhb/5into15#2]
You can now mark Twitter bots as being automated, and associated with another account - [instructions here](https://twittercommunity.com/t/introducing-automated-account-labeling/166830). It might be a nice thing to add to the account :-)

**Comment by anotherrhb** [comment]
Thanks for this tip @andypiper I'll look at doing it. I see in the note it'll be a requirement at some point, not just a nice to have. I guess this is to hopefully reduce some of the junk/spam bots that might be operating out there?

**Comment by anotherrhb** [comment]
Done now, thanks for suggestion @andypiper
